### ISSUE TITLE
Update documentation to include Rust compilation steps

### ISSUE THREAD

**Issue by Kaos-Industries** [adrianboston/srcset#3]
I'm guessing this new Rust version requires a compilation and is no longer run using `srcset.sh`, but the current `README.md` seems a copy of the old `srcset.sh` version. If there is a binary for this Rust version, I seem to have missed it.

**Comment by adrianboston** [comment]
It typically needs compilation. There is a OSX DMG under Versions.

The srcset.sh script still works but deprecated. No longer work on it. The rust version is heaps faster. Doesnt require imagemagick at all. In fact, if you can compile imagemagick on your machine then you can likely compile rust. Its alot easier than any C++ project. The dependencies are pulled in perfectly. There is no cmake. 

And Ill try to add quality into this Rust version. Just noticed its possible. It was hidden under Jpeg codecs.

**Comment by Kaos-Industries** [comment]
Unfortunately I found that the srcset.sh didn't work for me, it gave me filename issues despite using a syntactically identical to the README. 

This persuaded me to try compiling the Rust version, and I managed to compile an `.exe` on Cygwin a few hours after I posted this issue, although I did already have a working minGW cross-compiling toolchain set up. Still, it was the easiest/fastest cross-compilation I've done in a while. 

Yes, if the concerns of the SmashingMagazine article referenced in #2 can be alleviated in this version of the tool, that would go a long way to alleviating my concerns about using an IM-based tool in a build process for one of my live sites.

**Comment by adrianboston** [comment]
I haven't touched on the script for a long long time. Please tell me if it works on Windows. Im a OSX and Linux person so many assumptions like the default output path `/tmp/srcset` and the use of path brackets / versus Windows \ .

**Comment by adrianboston** [comment]
When you do cargo build make sure to use `release` or you will get dead slow unoptimzed code

`cargo build --release`

The exe will be under target/release

Then try 

`target/release/srcset -r /Disk -vz -p var/www/html` -j

-j is for parallel jobs

**Comment by adrianboston** [comment]
Instructions for building in readme

**Comment by Kaos-Industries** [comment]
> When you do cargo build make sure to use `release` or you will get dead slow unoptimzed code
> 
> `cargo build --release`
> 
> The exe will be under target/release
> 
> Then try
> 
> `target/release/srcset -r /Disk -vz -p var/www/html` -j
> 
> -j is for parallel jobs

That makes a lot of sense, now that I think back I remember running something like `cargo run` and each run working fine but taking a few minutes, I had disregarded the slow run time because I was just in a rush to get something working at the time.

**Comment by adrianboston** [comment]
The scrscet.sh is a unix script so your problems are likely due to a forward slash back slash incompatibility. Apparently its possible to use unix forward slash in [windows](https://www.howtogeek.com/261591/how-to-create-and-run-bash-shell-scripts-on-windows-10).

Note that the same might happen with the Rust executable on Windows as the `-o --out` option is defaulted to `/tmp/scrset` that do have forward slashes. The only way to avoid that is use the current path but i did not want to clutter the current path with images if the executable was run by mistake.

If it is a problem specify the outpath as such:

`target/release/srcset -r c:\my\images --verbose  --jobs --out c:\my\path\`
